language: dart
dart:
  - 1.24.2
script:
  - dart tool/build.dart
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
  - pub run dart_dev test --web-compiler=dartdevc -p chrome
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
