language: dart
dart: [stable]
sudo: required
addons:
  chrome: stable
script:
  - pub run build_runner build --delete-conflicting-outputs
  - dartfmt -n --set-exit-if-changed lib/
  - dartanalyzer --fatal-warnings --fatal-infos lib/
  - pub run build_runner test --delete-conflicting-outputs
  - pub run build_runner test --delete-conflicting-outputs -- -p chrome
  - pub run build_runner test --release --delete-conflicting-outputs -- -p chrome
