name: built_redux
version: 7.4.1
description:
  A state management library written in dart that enforces immutability
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.29.0 <0.32.0'
  build: '>=0.10.0 <0.12.0'
  built_collection: '>=1.0.0 <4.0.0'
  built_value: '>=4.1.0 < 6.0.0'
  source_gen: ^0.7.0
  test: ^0.12.0

dev_dependencies:
  build_runner: ^0.6.0
  built_value_generator: ^5.0.0
  dart_dev: ^1.9.2
  dart_style: ^1.0.0
  coverage: ^0.9.3

environment:
  sdk: ">=1.17.1 <2.0.0"

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
