name: built_redux
version: 8.0.0-nullsafety.0
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.40.0 <2.0.0'
  build: ^2.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.0
  source_gen: ^0.9.4+6
  test: ^1.16.0

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  built_value_generator: ^8.0.0
  build_web_compilers: ^2.7.1
  workiva_analysis_options: ^1.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
# dependency_overrides:
#   built_value_generator:
#     path: ../built_value.dart/built_value_generator
