name: built_redux
version: 8.0.9
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^10.0.0
  build: ^4.0.4
  built_collection: ^5.1.1
  built_value: ^8.10.1
  source_gen: ^4.1.2
  test: ^1.29.0

dev_dependencies:
  build_runner: ^2.10.5
  build_test: ^3.5.5
  built_value_generator: ^8.12.2
  build_web_compilers: ^4.4.7
  workiva_analysis_options: ^1.2.0
