name: built_redux
version: 7.5.3
description:
  A state management library written in dart that enforces immutability
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.33.0 <0.37.0'
  build: ^1.0.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  source_gen: ^0.9.0
  test: '>=0.12.0 <2.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  built_value_generator: ^6.0.0
  build_web_compilers: ^2.1.1

environment:
  sdk: '>=2.0.0-dev <3.0.0'
